version: "3.9"

services:
  hub:
    build: ./hub
    container_name: panic_hub
    ports:
      - "8000:8000"
    depends_on:
      - orchestrator
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8001

  orchestrator:
    build: ./orchestrator
    container_name: panic_orchestrator
    ports:
      - "8001:8001"
    depends_on:
      - mock_panic_bot
    environment:
      - MOCK_BOT_URL=http://mock_panic_bot:8002

  mock_panic_bot:
    build: ./mock_panic_bot
    container_name: panic_mock_bot
    ports:
      - "8002:8002"
